# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Cabrillo Robotics Club
# Description of the Site
description: Student led robotics club at Cabrillo College in Aptos, California. 
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Robotics, Cabrillo Robotics Club, Lazer Shark, SeaHawk II, SeaHawk, Hydrozoa, MATE, RoboSub, ROV, AUV
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/CabrilloRoboticsClub/cabrillorobotics.github.io/f0905cbecd1b1167085058ae4c5352152cb95fad/assets/images/hero.webp

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: cabrillorobotics@gmail.com
facebook_username: /
twitter_username: /
instagram_username: cabrillorobotics
linkedin_username: /
github_username:  CabrilloRoboticsClub
youtube_channel_id: UC7C8mbnPujbr6cxQMaxRVWw
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
